# MongoDB URI
MONGODB_URI = ""

# All Databases Name
AI_TUTOR_IQAN_DATABASE_NAME = ""

# All collection names
DOMAIN_COLLECTION_NAME = ""
COURSES_COLLECTION_NAME = ""
MODULES_COLLECTION_NAME = ""
LESSONS_COLLECTION_NAME = ""
ON_DEMAND_DOMAINS_ANALYSIS = ""
SEGMENTS_COLLECTION_NAME = ""
LIVE_COURSES_COLLECTION_NAME = ""
PREDEFINED_COURSES_COLLECTION_NAME = ""
COMBINED_COURSES_COLLECTION_NAME = ""


